/aruco_node:
  ros__parameters:
    # 1. Update marker_ids to list ALL IDs you want to track
    marker_ids: [1, 2, 10]
    
    #2. Use marker_size_map to specify the size for each ID
    marker_size_map: {
        1: 0.10,  # Base marker is 150mm
        2: 0.10,
        10: 0.15  # Object marker is 100mm (0.1m)
    }
    
    # The single marker_size parameter is now ignored if an ID is in the map, 
    # but you can leave it for backward compatibility or as a default:
    #marker_size: 0.15 
    
    # --- Other parameters remain the same ---
    aruco_dictionary_id: DICT_5X5_250
    image_topic: /camera1/image_raw
    camera_info_topic: /camera1/camera_info